
INCLUDEPATH += displays

FORMS   += displays/dspAllocations.ui \
           displays/dspAPApplications.ui \
           displays/dspAPOpenItemsByVendor.ui \
           displays/dspARApplications.ui \
           displays/dspBOMBase.ui \
           displays/dspBriefEarnedCommissions.ui \
           displays/dspCapacityUOMsByParameter.ui \
           displays/dspCostedBOMBase.ui \
           displays/dspCostedSummarizedBOM.ui \
           displays/dspCountSlipsByWarehouse.ui \
           displays/dspCountTagsBase.ui \
           displays/dspCustomerARHistory.ui \
           displays/dspDepositsRegister.ui \
           displays/dspDetailedInventoryHistoryByLocation.ui \
           displays/dspDetailedInventoryHistoryByLotSerial.ui \
           displays/dspEarnedCommissions.ui \
           displays/dspExpediteExceptionsByPlannerCode.ui \
           displays/dspExpiredInventoryByClassCode.ui \
           displays/dspFreightPricesByCustomer.ui \
           displays/dspFreightPricesByCustomerType.ui \
           displays/dspFrozenItemSites.ui \
           displays/dspGLSeries.ui \
           displays/dspGLTransactions.ui \
           displays/dspIncidentsByCRMAccount.ui \
           displays/dspIndentedWhereUsed.ui \
           displays/dspInvalidBillsOfMaterials.ui \
           displays/dspInventoryAvailability.ui \
           displays/dspInventoryAvailabilityByCustomerType.ui \
           displays/dspInventoryAvailabilityBySalesOrder.ui \
           displays/dspInventoryAvailabilityByWorkOrder.ui \
           displays/dspInventoryLocator.ui \
           displays/dspInvoiceRegister.ui \
           displays/dspItemCostDetail.ui \
           displays/dspItemCostHistory.ui \
           displays/dspItemCostSummary.ui \
           displays/dspItemCostsByClassCode.ui \
           displays/dspJobCosting.ui \
           displays/dspMaterialUsageVarianceByBOMItem.ui \
           displays/dspMaterialUsageVarianceByComponentItem.ui \
           displays/dspMaterialUsageVarianceByItem.ui \
           displays/dspMaterialUsageVarianceByWarehouse.ui \
           displays/dspMaterialUsageVarianceByWorkOrder.ui \
           displays/dspOrderActivityByProject.ui \
           displays/dspOrders.ui \
           displays/dspPartiallyShippedOrders.ui \
           displays/dspPendingAvailability.ui \
           displays/dspPendingBOMChanges.ui \
           displays/dspPoDeliveryDateVariancesByItem.ui \
           displays/dspPoDeliveryDateVariancesByVendor.ui \
           displays/dspPoHistory.ui \
           displays/dspPoItemReceivingsByDate.ui \
           displays/dspPoItemReceivingsByItem.ui \
           displays/dspPoItemReceivingsByVendor.ui \
           displays/dspPoItemsByDate.ui \
           displays/dspPoItemsByItem.ui \
           displays/dspPoItemsByVendor.ui \
           displays/dspPoPriceVariancesByItem.ui \
           displays/dspPoPriceVariancesByVendor.ui \
           displays/dspPoReturnsByVendor.ui \
           displays/dspPOsByDate.ui \
           displays/dspPOsByVendor.ui \
           displays/dspPricesByCustomer.ui \
           displays/dspPricesByCustomerType.ui \
           displays/dspPricesByItem.ui \
           displays/dspPurchaseReqsByItem.ui \
           displays/dspPurchaseReqsByPlannerCode.ui \
           displays/dspQOH.ui \
           displays/dspQOHByLocation.ui \
           displays/dspQuotesByCustomer.ui \
           displays/dspQuotesByItem.ui \
           displays/dspReorderExceptionsByPlannerCode.ui \
           displays/dspReservations.ui \
           displays/dspRunningAvailability.ui \
           displays/dspSalesOrdersByCustomer.ui \
           displays/dspSalesOrdersByCustomerPO.ui \
           displays/dspSalesOrdersByItem.ui \
           displays/dspSalesOrdersByParameterList.ui \
           displays/dspSalesOrderStatus.ui \
           displays/dspShipmentsBase.ui \
           displays/dspShipmentsByDate.ui \
           displays/dspSingleLevelWhereUsed.ui \
           displays/dspSlowMovingInventoryByClassCode.ui \
           displays/dspStandardJournalHistory.ui \
           displays/dspSubstituteAvailabilityByItem.ui \
           displays/dspSummarizedBacklogByWarehouse.ui \
           displays/dspSummarizedBankrecHistory.ui \
           displays/dspSummarizedGLTransactions.ui \
           displays/dspSummarizedSales.ui \
           displays/dspTimePhasedAvailability.ui \
           displays/dspTimePhasedBookings.ui \
           displays/dspTimePhasedOpenAPItems.ui \
           displays/dspTimePhasedOpenARItems.ui \
           displays/dspTimePhasedUsageStatisticsByItem.ui \
           displays/dspTodoByUserAndIncident.ui \
           displays/dspUnbalancedQOHByClassCode.ui \
           displays/dspUndefinedManufacturedItems.ui \
           displays/dspUninvoicedReceivings.ui \
           displays/dspUnusedPurchasedItems.ui \
           displays/dspValidLocationsByItem.ui \
           displays/dspVendorAPHistory.ui \
           displays/dspVoucherRegister.ui \
           displays/dspWoHistoryByClassCode.ui \
           displays/dspWoHistoryByItem.ui \
           displays/dspWoHistoryByNumber.ui \
           displays/dspWoMaterialsByItem.ui \
           displays/dspWoMaterialsByWorkOrder.ui \

HEADERS += displays/dspAllocations.h \
           displays/dspAPApplications.h \
           displays/dspAPOpenItemsByVendor.h \
           displays/dspARApplications.h \
           displays/dspBOMBase.h \
           displays/dspBacklog.h \
           displays/dspBookings.h \
           displays/dspBriefEarnedCommissions.h \
           displays/dspBriefSalesHistory.h \
           displays/dspCapacityUOMsByClassCode.h \
           displays/dspCapacityUOMsByParameter.h \
           displays/dspCapacityUOMsByProductCategory.h \
           displays/dspCostedBOMBase.h \
           displays/dspCostedIndentedBOM.h \
           displays/dspCostedSingleLevelBOM.h \
           displays/dspCostedSummarizedBOM.h \
           displays/dspCountSlipsByWarehouse.h \
           displays/dspCountTagsBase.h \
           displays/dspCountTagsByClassCode.h \
           displays/dspCountTagsByItem.h \
           displays/dspCountTagsByWarehouse.h \
           displays/dspCustomerARHistory.h \
           displays/dspDepositsRegister.h \
           displays/dspDetailedInventoryHistoryByLocation.h \
           displays/dspDetailedInventoryHistoryByLotSerial.h \
           displays/dspEarnedCommissions.h \
           displays/dspExpediteExceptionsByPlannerCode.h \
           displays/dspExpiredInventoryByClassCode.h \
           displays/dspFreightPricesByCustomer.h \
           displays/dspFreightPricesByCustomerType.h \
           displays/dspFrozenItemSites.h \
           displays/dspGLSeries.h \
           displays/dspGLTransactions.h \
           displays/dspIncidentsByCRMAccount.h \
           displays/dspIndentedBOM.h \
           displays/dspIndentedWhereUsed.h \
           displays/dspInvalidBillsOfMaterials.h \
           displays/dspInventoryAvailability.h \
           displays/dspInventoryAvailabilityByCustomerType.h \
           displays/dspInventoryAvailabilityBySalesOrder.h \
           displays/dspInventoryAvailabilityByWorkOrder.h \
           displays/dspInventoryHistory.h \
           displays/dspInventoryLocator.h \
           displays/dspInvoiceRegister.h \
           displays/dspItemCostDetail.h \
           displays/dspItemCostHistory.h \
           displays/dspItemCostSummary.h \
           displays/dspItemCostsByClassCode.h \
           displays/dspItemsWithoutItemSources.h \
           displays/dspJobCosting.h \
           displays/dspJournals.h \
           displays/dspMaterialUsageVarianceByBOMItem.h \
           displays/dspMaterialUsageVarianceByComponentItem.h \
           displays/dspMaterialUsageVarianceByItem.h \
           displays/dspMaterialUsageVarianceByWarehouse.h \
           displays/dspMaterialUsageVarianceByWorkOrder.h \
           displays/dspOrderActivityByProject.h \
           displays/dspOrders.h \
           displays/dspPartiallyShippedOrders.h \
           displays/dspPendingAvailability.h \
           displays/dspPendingBOMChanges.h \
           displays/dspPlannedOrders.h \
           displays/dspPoDeliveryDateVariancesByItem.h \
           displays/dspPoDeliveryDateVariancesByVendor.h \
           displays/dspPoHistory.h \
           displays/dspPoItemReceivingsByDate.h \
           displays/dspPoItemReceivingsByItem.h \
           displays/dspPoItemReceivingsByVendor.h \
           displays/dspPoItemsByDate.h \
           displays/dspPoItemsByItem.h \
           displays/dspPoItemsByVendor.h \
           displays/dspPoPriceVariancesByItem.h \
           displays/dspPoPriceVariancesByVendor.h \
           displays/dspPoReturnsByVendor.h \
           displays/dspPOsByDate.h \
           displays/dspPOsByVendor.h \
           displays/dspPricesByCustomer.h \
           displays/dspPricesByCustomerType.h \
           displays/dspPricesByItem.h \
           displays/dspPurchaseReqsByItem.h \
           displays/dspPurchaseReqsByPlannerCode.h \
           displays/dspQOH.h \
           displays/dspQOHByLocation.h \
           displays/dspQuotesByCustomer.h \
           displays/dspQuotesByItem.h \
           displays/dspReorderExceptionsByPlannerCode.h \
           displays/dspReservations.h \
           displays/dspRunningAvailability.h \
           displays/dspSalesHistory.h \
           displays/dspSalesOrdersByCustomer.h \
           displays/dspSalesOrdersByCustomerPO.h \
           displays/dspSalesOrdersByItem.h \
           displays/dspSalesOrdersByParameterList.h \
           displays/dspSalesOrderStatus.h \
           displays/dspShipmentsBase.h \
           displays/dspShipmentsByDate.h \
           displays/dspShipmentsBySalesOrder.h \
           displays/dspShipmentsByShipment.h \
           displays/dspSingleLevelBOM.h \
           displays/dspSingleLevelWhereUsed.h \
           displays/dspSlowMovingInventoryByClassCode.h \
           displays/dspStandardJournalHistory.h \
           displays/dspSubstituteAvailabilityByItem.h \
           displays/dspSummarizedBacklogByWarehouse.h \
           displays/dspSummarizedBankrecHistory.h \
           displays/dspSummarizedBOM.h \
           displays/dspSummarizedGLTransactions.h \
           displays/dspSummarizedSales.h \
           displays/dspTimePhasedAvailability.h \
           displays/dspTimePhasedBookings.h \
           displays/dspTimePhasedOpenAPItems.h \
           displays/dspTimePhasedOpenARItems.h \
           displays/dspTimePhasedSales.h \
           displays/dspTimePhasedUsageStatisticsByItem.h \
           displays/dspTodoByUserAndIncident.h \
           displays/dspTrialBalances.h \
           displays/dspUnbalancedQOHByClassCode.h \
           displays/dspUndefinedManufacturedItems.h \
           displays/dspUninvoicedReceivings.h \
           displays/dspUnusedPurchasedItems.h \
           displays/dspUsageStatistics.h \
           displays/dspValidLocationsByItem.h \
           displays/dspVendorAPHistory.h \
           displays/dspVoucherRegister.h \
           displays/dspWoHistoryByClassCode.h \
           displays/dspWoHistoryByItem.h \
           displays/dspWoHistoryByNumber.h \
           displays/dspWoMaterialsByItem.h \
           displays/dspWoMaterialsByWorkOrder.h \
           displays/dspWoSchedule.h \

SOURCES += displays/dspAllocations.cpp \
           displays/dspAPApplications.cpp \
           displays/dspAPOpenItemsByVendor.cpp \
           displays/dspARApplications.cpp \
           displays/dspBOMBase.cpp \
           displays/dspBacklog.cpp \
           displays/dspBookings.cpp \
           displays/dspBriefEarnedCommissions.cpp \
           displays/dspBriefSalesHistory.cpp \
           displays/dspCapacityUOMsByClassCode.cpp \
           displays/dspCapacityUOMsByParameter.cpp \
           displays/dspCapacityUOMsByProductCategory.cpp \
           displays/dspCostedBOMBase.cpp \
           displays/dspCostedIndentedBOM.cpp \
           displays/dspCostedSingleLevelBOM.cpp \
           displays/dspCostedSummarizedBOM.cpp \
           displays/dspCountSlipsByWarehouse.cpp \
           displays/dspCountTagsBase.cpp \
           displays/dspCountTagsByClassCode.cpp \
           displays/dspCountTagsByItem.cpp \
           displays/dspCountTagsByWarehouse.cpp \
           displays/dspCustomerARHistory.cpp \
           displays/dspDepositsRegister.cpp \
           displays/dspDetailedInventoryHistoryByLocation.cpp \
           displays/dspDetailedInventoryHistoryByLotSerial.cpp \
           displays/dspEarnedCommissions.cpp \
           displays/dspExpediteExceptionsByPlannerCode.cpp \
           displays/dspExpiredInventoryByClassCode.cpp \
           displays/dspFreightPricesByCustomer.cpp \
           displays/dspFreightPricesByCustomerType.cpp \
           displays/dspFrozenItemSites.cpp \
           displays/dspGLSeries.cpp \
           displays/dspGLTransactions.cpp \
           displays/dspIncidentsByCRMAccount.cpp \
           displays/dspIndentedBOM.cpp \
           displays/dspIndentedWhereUsed.cpp \
           displays/dspInvalidBillsOfMaterials.cpp \
           displays/dspInventoryAvailability.cpp \
           displays/dspInventoryAvailabilityByCustomerType.cpp \
           displays/dspInventoryAvailabilityBySalesOrder.cpp \
           displays/dspInventoryAvailabilityByWorkOrder.cpp \
           displays/dspInventoryHistory.cpp \
           displays/dspInventoryLocator.cpp \
           displays/dspInvoiceRegister.cpp \
           displays/dspItemCostDetail.cpp \
           displays/dspItemCostHistory.cpp \
           displays/dspItemCostSummary.cpp \
           displays/dspItemCostsByClassCode.cpp \
           displays/dspItemsWithoutItemSources.cpp \
           displays/dspJobCosting.cpp \
           displays/dspJournals.cpp \
           displays/dspMaterialUsageVarianceByBOMItem.cpp \
           displays/dspMaterialUsageVarianceByComponentItem.cpp \
           displays/dspMaterialUsageVarianceByItem.cpp \
           displays/dspMaterialUsageVarianceByWarehouse.cpp \
           displays/dspMaterialUsageVarianceByWorkOrder.cpp \
           displays/dspTimePhasedOpenAPItems.cpp \
           displays/dspTimePhasedOpenARItems.cpp \
           displays/dspOrderActivityByProject.cpp \
           displays/dspOrders.cpp \
           displays/dspPartiallyShippedOrders.cpp \
           displays/dspPendingAvailability.cpp \
           displays/dspPendingBOMChanges.cpp \
           displays/dspPlannedOrders.cpp \
           displays/dspPoDeliveryDateVariancesByItem.cpp \
           displays/dspPoDeliveryDateVariancesByVendor.cpp \
           displays/dspPoHistory.cpp \
           displays/dspPoItemReceivingsByDate.cpp \
           displays/dspPoItemReceivingsByItem.cpp \
           displays/dspPoItemReceivingsByVendor.cpp \
           displays/dspPoItemsByDate.cpp \
           displays/dspPoItemsByItem.cpp \
           displays/dspPoItemsByVendor.cpp \
           displays/dspPoPriceVariancesByItem.cpp \
           displays/dspPoPriceVariancesByVendor.cpp \
           displays/dspPoReturnsByVendor.cpp \
           displays/dspPOsByDate.cpp \
           displays/dspPOsByVendor.cpp \
           displays/dspPricesByCustomer.cpp \
           displays/dspPricesByCustomerType.cpp \
           displays/dspPricesByItem.cpp \
           displays/dspPurchaseReqsByItem.cpp \
           displays/dspPurchaseReqsByPlannerCode.cpp \
           displays/dspQOH.cpp \
           displays/dspQOHByLocation.cpp \
           displays/dspQuotesByCustomer.cpp \
           displays/dspQuotesByItem.cpp \
           displays/dspReorderExceptionsByPlannerCode.cpp \
           displays/dspReservations.cpp \
           displays/dspRunningAvailability.cpp \
           displays/dspSalesHistory.cpp \
           displays/dspSalesOrdersByCustomer.cpp \
           displays/dspSalesOrdersByCustomerPO.cpp \
           displays/dspSalesOrdersByItem.cpp \
           displays/dspSalesOrdersByParameterList.cpp \
           displays/dspSalesOrderStatus.cpp \
           displays/dspShipmentsBase.cpp \
           displays/dspShipmentsByDate.cpp \
           displays/dspShipmentsBySalesOrder.cpp \
           displays/dspShipmentsByShipment.cpp \
           displays/dspSingleLevelBOM.cpp \
           displays/dspSingleLevelWhereUsed.cpp \
           displays/dspSlowMovingInventoryByClassCode.cpp \
           displays/dspStandardJournalHistory.cpp \
           displays/dspSubstituteAvailabilityByItem.cpp \
           displays/dspSummarizedBacklogByWarehouse.cpp \
           displays/dspSummarizedBankrecHistory.cpp \
           displays/dspSummarizedBOM.cpp \
           displays/dspSummarizedGLTransactions.cpp \
           displays/dspSummarizedSales.cpp \
           displays/dspTimePhasedAvailability.cpp \
           displays/dspTimePhasedBookings.cpp \
           displays/dspTimePhasedSales.cpp \
           displays/dspTimePhasedUsageStatisticsByItem.cpp \
           displays/dspTodoByUserAndIncident.cpp \
           displays/dspTrialBalances.cpp \
           displays/dspUnbalancedQOHByClassCode.cpp \
           displays/dspUndefinedManufacturedItems.cpp \
           displays/dspUninvoicedReceivings.cpp \
           displays/dspUnusedPurchasedItems.cpp \
           displays/dspUsageStatistics.cpp \
           displays/dspValidLocationsByItem.cpp \
           displays/dspVendorAPHistory.cpp \
           displays/dspVoucherRegister.cpp \
           displays/dspWoHistoryByClassCode.cpp \
           displays/dspWoHistoryByItem.cpp \
           displays/dspWoHistoryByNumber.cpp \
           displays/dspWoMaterialsByItem.cpp \
           displays/dspWoMaterialsByWorkOrder.cpp \
           displays/dspWoSchedule.cpp \

