
INCLUDEPATH += displays

FORMS   += displays/dspAllocations.ui \
           displays/dspAPApplications.ui \
           displays/dspAPOpenItemsByVendor.ui \
           displays/dspARApplications.ui \
           displays/dspBOMBase.ui \
           displays/dspBacklogByCustomer.ui \
           displays/dspBacklogByItem.ui \
           displays/dspBacklogByParameterList.ui \
           displays/dspBacklogBySalesOrder.ui \
           displays/dspBookingsByCustomer.ui \
           displays/dspBookingsByCustomerGroup.ui \
           displays/dspBookingsByItem.ui \
           displays/dspBookingsByProductCategory.ui \
           displays/dspBookingsBySalesRep.ui \
           displays/dspBookingsByShipTo.ui \
           displays/dspBriefEarnedCommissions.ui \
           displays/dspBriefSalesHistoryByCustomer.ui \
           displays/dspBriefSalesHistoryByCustomerType.ui \
           displays/dspBriefSalesHistoryBySalesRep.ui \
           displays/dspCapacityUOMsByParameter.ui \
           displays/dspCostedBOMBase.ui \
           displays/dspCostedSummarizedBOM.ui \
           displays/dspCountSlipsByWarehouse.ui \
           displays/dspCountTagsBase.ui \
           displays/dspCustomerARHistory.ui \
           displays/dspCustomerInformationExport.ui \
           displays/dspCustomersByCharacteristic.ui \
           displays/dspCustomersByCustomerType.ui \
           displays/dspDepositsRegister.ui \
           displays/dspDetailedInventoryHistoryByLocation.ui \
           displays/dspDetailedInventoryHistoryByLotSerial.ui \
           displays/dspEarnedCommissions.ui \
           displays/dspExpediteExceptionsByPlannerCode.ui \
           displays/dspExpiredInventoryByClassCode.ui \
           displays/dspFreightPricesByCustomer.ui \
           displays/dspFreightPricesByCustomerType.ui \
           displays/dspFrozenItemSites.ui \
           displays/dspGLSeries.ui \
           displays/dspGLTransactions.ui \
           displays/dspIncidentsByCRMAccount.ui \
           displays/dspIndentedWhereUsed.ui \
           displays/dspInvalidBillsOfMaterials.ui \
           displays/dspInventoryAvailabilityByCustomerType.ui \
           displays/dspInventoryAvailabilityByItem.ui \
           displays/dspInventoryAvailabilityByParameterList.ui \
           displays/dspInventoryAvailabilityBySalesOrder.ui \
           displays/dspInventoryAvailabilityBySourceVendor.ui \
           displays/dspInventoryAvailabilityByWorkOrder.ui \
           displays/dspInventoryHistoryBase.ui \
           displays/dspInventoryLocator.ui \
           displays/dspInvoiceRegister.ui \
           displays/dspItemCostDetail.ui \
           displays/dspItemCostHistory.ui \
           displays/dspItemCostSummary.ui \
           displays/dspItemCostsByClassCode.ui \
           displays/dspItemsByCharacteristic.ui \
           displays/dspItemsByParameter.ui \
           displays/dspItemSitesByItem.ui \
           displays/dspItemSitesByParameterList.ui \
           displays/dspItemSourcesByItem.ui \
           displays/dspItemSourcesByVendor.ui \
           displays/dspJobCosting.ui \
           displays/dspMaterialUsageVarianceByBOMItem.ui \
           displays/dspMaterialUsageVarianceByComponentItem.ui \
           displays/dspMaterialUsageVarianceByItem.ui \
           displays/dspMaterialUsageVarianceByWarehouse.ui \
           displays/dspMaterialUsageVarianceByWorkOrder.ui \
           displays/dspOrderActivityByProject.ui \
           displays/dspOrders.ui \
           displays/dspPartiallyShippedOrders.ui \
           displays/dspPendingAvailability.ui \
           displays/dspPendingBOMChanges.ui \
           displays/dspPlannedOrdersByItem.ui \
           displays/dspPlannedOrdersByPlannerCode.ui \
           displays/dspPoDeliveryDateVariancesByItem.ui \
           displays/dspPoDeliveryDateVariancesByVendor.ui \
           displays/dspPoHistory.ui \
           displays/dspPoItemReceivingsByDate.ui \
           displays/dspPoItemReceivingsByItem.ui \
           displays/dspPoItemReceivingsByVendor.ui \
           displays/dspPoItemsByDate.ui \
           displays/dspPoItemsByItem.ui \
           displays/dspPoItemsByVendor.ui \
           displays/dspPoPriceVariancesByItem.ui \
           displays/dspPoPriceVariancesByVendor.ui \
           displays/dspPoReturnsByVendor.ui \
           displays/dspPOsByDate.ui \
           displays/dspPOsByVendor.ui \
           displays/dspPricesByCustomer.ui \
           displays/dspPricesByCustomerType.ui \
           displays/dspPricesByItem.ui \
           displays/dspPurchaseReqsByItem.ui \
           displays/dspPurchaseReqsByPlannerCode.ui \
           displays/dspQOHByItem.ui \
           displays/dspQOHByLocation.ui \
           displays/dspQOHByParameterList.ui \
           displays/dspQuotesByCustomer.ui \
           displays/dspQuotesByItem.ui \
           displays/dspReorderExceptionsByPlannerCode.ui \
           displays/dspReservations.ui \
           displays/dspRunningAvailability.ui \
           displays/dspSalesHistoryByBilltoName.ui \
           displays/dspSalesHistoryByCustomer.ui \
           displays/dspSalesHistoryByItem.ui \
           displays/dspSalesHistoryByParameterList.ui \
           displays/dspSalesHistoryBySalesrep.ui \
           displays/dspSalesHistoryByShipTo.ui \
           displays/dspSalesOrdersByCustomer.ui \
           displays/dspSalesOrdersByCustomerPO.ui \
           displays/dspSalesOrdersByItem.ui \
           displays/dspSalesOrdersByParameterList.ui \
           displays/dspSalesOrderStatus.ui \
           displays/dspShipmentsBase.ui \
           displays/dspShipmentsByDate.ui \
           displays/dspSingleLevelWhereUsed.ui \
           displays/dspSlowMovingInventoryByClassCode.ui \
           displays/dspStandardJournalHistory.ui \
           displays/dspSubstituteAvailabilityByItem.ui \
           displays/dspSummarizedBacklogByWarehouse.ui \
           displays/dspSummarizedBankrecHistory.ui \
           displays/dspSummarizedGLTransactions.ui \
           displays/dspSummarizedSalesByCustomer.ui \
           displays/dspSummarizedSalesByCustomerByItem.ui \
           displays/dspSummarizedSalesByCustomerType.ui \
           displays/dspSummarizedSalesByCustomerTypeByItem.ui \
           displays/dspSummarizedSalesByItem.ui \
           displays/dspSummarizedSalesBySalesRep.ui \
           displays/dspSummarizedSalesHistoryByShippingZone.ui \
           displays/dspTimePhasedAvailability.ui \
           displays/dspTimePhasedBookingsByCustomer.ui \
           displays/dspTimePhasedBookingsByItem.ui \
           displays/dspTimePhasedBookingsByProductCategory.ui \
           displays/dspTimePhasedSalesByCustomer.ui \
           displays/dspTimePhasedSalesByCustomerByItem.ui \
           displays/dspTimePhasedSalesByCustomerGroup.ui \
           displays/dspTimePhasedSalesByItem.ui \
           displays/dspTimePhasedSalesByProductCategory.ui \
           displays/dspTimePhasedUsageStatisticsByItem.ui \
           displays/dspTodoByUserAndIncident.ui \
           displays/dspUnbalancedQOHByClassCode.ui \
           displays/dspUndefinedManufacturedItems.ui \
           displays/dspUninvoicedReceivings.ui \
           displays/dspUnusedPurchasedItems.ui \
           displays/dspUsageStatisticsBase.ui \
           displays/dspValidLocationsByItem.ui \
           displays/dspVendorAPHistory.ui \
           displays/dspVoucherRegister.ui \
           displays/dspWoHistoryByClassCode.ui \
           displays/dspWoHistoryByItem.ui \
           displays/dspWoHistoryByNumber.ui \
           displays/dspWoMaterialsByItem.ui \
           displays/dspWoMaterialsByWorkOrder.ui \
           displays/dspWoScheduleByItem.ui \
           displays/dspWoScheduleByParameterList.ui \
           displays/dspWoScheduleByWorkOrder.ui \
           displays/dspWoSoStatus.ui \
           displays/dspWoSoStatusMismatch.ui

HEADERS += displays/dspAllocations.h \
           displays/dspAPApplications.h \
           displays/dspAPOpenItemsByVendor.h \
           displays/dspARApplications.h \
           displays/dspBOMBase.h \
           displays/dspBacklogByCustomer.h \
           displays/dspBacklogByItem.h \
           displays/dspBacklogByParameterList.h \
           displays/dspBacklogBySalesOrder.h \
           displays/dspBookingsByCustomer.h \
           displays/dspBookingsByCustomerGroup.h \
           displays/dspBookingsByItem.h \
           displays/dspBookingsByProductCategory.h \
           displays/dspBookingsBySalesRep.h \
           displays/dspBookingsByShipTo.h \
           displays/dspBriefEarnedCommissions.h \
           displays/dspBriefSalesHistoryByCustomer.h \
           displays/dspBriefSalesHistoryByCustomerType.h \
           displays/dspBriefSalesHistoryBySalesRep.h \
           displays/dspCapacityUOMsByClassCode.h \
           displays/dspCapacityUOMsByParameter.h \
           displays/dspCapacityUOMsByProductCategory.h \
           displays/dspCostedBOMBase.h \
           displays/dspCostedIndentedBOM.h \
           displays/dspCostedSingleLevelBOM.h \
           displays/dspCostedSummarizedBOM.h \
           displays/dspCountSlipsByWarehouse.h \
           displays/dspCountTagsBase.h \
           displays/dspCountTagsByClassCode.h \
           displays/dspCountTagsByItem.h \
           displays/dspCountTagsByWarehouse.h \
           displays/dspCustomerARHistory.h \
           displays/dspCustomerInformationExport.h \
           displays/dspCustomersByCharacteristic.h \
           displays/dspCustomersByCustomerType.h \
           displays/dspDepositsRegister.h \
           displays/dspDetailedInventoryHistoryByLocation.h \
           displays/dspDetailedInventoryHistoryByLotSerial.h \
           displays/dspEarnedCommissions.h \
           displays/dspExpediteExceptionsByPlannerCode.h \
           displays/dspExpiredInventoryByClassCode.h \
           displays/dspFreightPricesByCustomer.h \
           displays/dspFreightPricesByCustomerType.h \
           displays/dspFrozenItemSites.h \
           displays/dspGLSeries.h \
           displays/dspGLTransactions.h \
           displays/dspIncidentsByCRMAccount.h \
           displays/dspIndentedBOM.h \
           displays/dspIndentedWhereUsed.h \
           displays/dspInvalidBillsOfMaterials.h \
           displays/dspInventoryAvailabilityByCustomerType.h \
           displays/dspInventoryAvailabilityByItem.h \
           displays/dspInventoryAvailabilityByParameterList.h \
           displays/dspInventoryAvailabilityBySalesOrder.h \
           displays/dspInventoryAvailabilityBySourceVendor.h \
           displays/dspInventoryAvailabilityByWorkOrder.h \
           displays/dspInventoryHistoryBase.h \
           displays/dspInventoryHistoryByItem.h \
           displays/dspInventoryHistoryByOrderNumber.h \
           displays/dspInventoryHistoryByParameterList.h \
           displays/dspInventoryLocator.h \
           displays/dspInvoiceRegister.h \
           displays/dspItemCostDetail.h \
           displays/dspItemCostHistory.h \
           displays/dspItemCostSummary.h \
           displays/dspItemCostsByClassCode.h \
           displays/dspItemsByCharacteristic.h \
           displays/dspItemsByClassCode.h \
           displays/dspItemsByParameter.h \
           displays/dspItemsByProductCategory.h \
           displays/dspItemSitesByItem.h \
           displays/dspItemSitesByParameterList.h \
           displays/dspItemSourcesByItem.h \
           displays/dspItemSourcesByVendor.h \
           displays/dspItemsWithoutItemSources.h \
           displays/dspJobCosting.h \
           displays/dspJournals.h \
           displays/dspMaterialUsageVarianceByBOMItem.h \
           displays/dspMaterialUsageVarianceByComponentItem.h \
           displays/dspMaterialUsageVarianceByItem.h \
           displays/dspMaterialUsageVarianceByWarehouse.h \
           displays/dspMaterialUsageVarianceByWorkOrder.h \
           displays/dspOrderActivityByProject.h \
           displays/dspOrders.h \
           displays/dspPartiallyShippedOrders.h \
           displays/dspPendingAvailability.h \
           displays/dspPendingBOMChanges.h \
           displays/dspPlannedOrdersByItem.h \
           displays/dspPlannedOrdersByPlannerCode.h \
           displays/dspPoDeliveryDateVariancesByItem.h \
           displays/dspPoDeliveryDateVariancesByVendor.h \
           displays/dspPoHistory.h \
           displays/dspPoItemReceivingsByDate.h \
           displays/dspPoItemReceivingsByItem.h \
           displays/dspPoItemReceivingsByVendor.h \
           displays/dspPoItemsByDate.h \
           displays/dspPoItemsByItem.h \
           displays/dspPoItemsByVendor.h \
           displays/dspPoPriceVariancesByItem.h \
           displays/dspPoPriceVariancesByVendor.h \
           displays/dspPoReturnsByVendor.h \
           displays/dspPOsByDate.h \
           displays/dspPOsByVendor.h \
           displays/dspPricesByCustomer.h \
           displays/dspPricesByCustomerType.h \
           displays/dspPricesByItem.h \
           displays/dspPurchaseReqsByItem.h \
           displays/dspPurchaseReqsByPlannerCode.h \
           displays/dspQOHByItem.h \
           displays/dspQOHByLocation.h \
           displays/dspQOHByParameterList.h \
           displays/dspQuotesByCustomer.h \
           displays/dspQuotesByItem.h \
           displays/dspReorderExceptionsByPlannerCode.h \
           displays/dspReservations.h \
           displays/dspRunningAvailability.h \
           displays/dspSalesHistoryByBilltoName.h \
           displays/dspSalesHistoryByCustomer.h \
           displays/dspSalesHistoryByItem.h \
           displays/dspSalesHistoryByParameterList.h \
           displays/dspSalesHistoryBySalesrep.h \
           displays/dspSalesHistoryByShipTo.h \
           displays/dspSalesOrdersByCustomer.h \
           displays/dspSalesOrdersByCustomerPO.h \
           displays/dspSalesOrdersByItem.h \
           displays/dspSalesOrdersByParameterList.h \
           displays/dspSalesOrderStatus.h \
           displays/dspShipmentsBase.h \
           displays/dspShipmentsByDate.h \
           displays/dspShipmentsBySalesOrder.h \
           displays/dspShipmentsByShipment.h \
           displays/dspSingleLevelBOM.h \
           displays/dspSingleLevelWhereUsed.h \
           displays/dspSlowMovingInventoryByClassCode.h \
           displays/dspStandardJournalHistory.h \
           displays/dspSubstituteAvailabilityByItem.h \
           displays/dspSummarizedBacklogByWarehouse.h \
           displays/dspSummarizedBankrecHistory.h \
           displays/dspSummarizedBOM.h \
           displays/dspSummarizedGLTransactions.h \
           displays/dspSummarizedSalesByCustomer.h \
           displays/dspSummarizedSalesByCustomerByItem.h \
           displays/dspSummarizedSalesByCustomerType.h \
           displays/dspSummarizedSalesByCustomerTypeByItem.h \
           displays/dspSummarizedSalesByItem.h \
           displays/dspSummarizedSalesBySalesRep.h \
           displays/dspSummarizedSalesHistoryByShippingZone.h \
           displays/dspTimePhasedAvailability.h \
           displays/dspTimePhasedBookingsByCustomer.h \
           displays/dspTimePhasedBookingsByItem.h \
           displays/dspTimePhasedBookingsByProductCategory.h \
           displays/dspTimePhasedSalesByCustomer.h \
           displays/dspTimePhasedSalesByCustomerByItem.h \
           displays/dspTimePhasedSalesByCustomerGroup.h \
           displays/dspTimePhasedSalesByItem.h \
           displays/dspTimePhasedSalesByProductCategory.h \
           displays/dspTimePhasedUsageStatisticsByItem.h \
           displays/dspTodoByUserAndIncident.h \
           displays/dspTrialBalances.h \
           displays/dspUnbalancedQOHByClassCode.h \
           displays/dspUndefinedManufacturedItems.h \
           displays/dspUninvoicedReceivings.h \
           displays/dspUnusedPurchasedItems.h \
           displays/dspUsageStatisticsBase.h \
           displays/dspUsageStatisticsByClassCode.h \
           displays/dspUsageStatisticsByItem.h \
           displays/dspUsageStatisticsByItemGroup.h \
           displays/dspUsageStatisticsByWarehouse.h \
           displays/dspValidLocationsByItem.h \
           displays/dspVendorAPHistory.h \
           displays/dspVoucherRegister.h \
           displays/dspWoHistoryByClassCode.h \
           displays/dspWoHistoryByItem.h \
           displays/dspWoHistoryByNumber.h \
           displays/dspWoMaterialsByItem.h \
           displays/dspWoMaterialsByWorkOrder.h \
           displays/dspWoScheduleByItem.h \
           displays/dspWoScheduleByParameterList.h \
           displays/dspWoScheduleByWorkOrder.h \
           displays/dspWoSoStatus.h \
           displays/dspWoSoStatusMismatch.h

SOURCES += displays/dspAllocations.cpp \
           displays/dspAPApplications.cpp \
           displays/dspAPOpenItemsByVendor.cpp \
           displays/dspARApplications.cpp \
           displays/dspBOMBase.cpp \
           displays/dspBacklogByCustomer.cpp \
           displays/dspBacklogByItem.cpp \
           displays/dspBacklogByParameterList.cpp \
           displays/dspBacklogBySalesOrder.cpp \
           displays/dspBookingsByCustomer.cpp \
           displays/dspBookingsByCustomerGroup.cpp \
           displays/dspBookingsByItem.cpp \
           displays/dspBookingsByProductCategory.cpp \
           displays/dspBookingsBySalesRep.cpp \
           displays/dspBookingsByShipTo.cpp \
           displays/dspBriefEarnedCommissions.cpp \
           displays/dspBriefSalesHistoryByCustomer.cpp \
           displays/dspBriefSalesHistoryByCustomerType.cpp \
           displays/dspBriefSalesHistoryBySalesRep.cpp \
           displays/dspCapacityUOMsByClassCode.cpp \
           displays/dspCapacityUOMsByParameter.cpp \
           displays/dspCapacityUOMsByProductCategory.cpp \
           displays/dspCostedBOMBase.cpp \
           displays/dspCostedIndentedBOM.cpp \
           displays/dspCostedSingleLevelBOM.cpp \
           displays/dspCostedSummarizedBOM.cpp \
           displays/dspCountSlipsByWarehouse.cpp \
           displays/dspCountTagsBase.cpp \
           displays/dspCountTagsByClassCode.cpp \
           displays/dspCountTagsByItem.cpp \
           displays/dspCountTagsByWarehouse.cpp \
           displays/dspCustomerARHistory.cpp \
           displays/dspCustomerInformationExport.cpp \
           displays/dspCustomersByCharacteristic.cpp \
           displays/dspCustomersByCustomerType.cpp \
           displays/dspDepositsRegister.cpp \
           displays/dspDetailedInventoryHistoryByLocation.cpp \
           displays/dspDetailedInventoryHistoryByLotSerial.cpp \
           displays/dspEarnedCommissions.cpp \
           displays/dspExpediteExceptionsByPlannerCode.cpp \
           displays/dspExpiredInventoryByClassCode.cpp \
           displays/dspFreightPricesByCustomer.cpp \
           displays/dspFreightPricesByCustomerType.cpp \
           displays/dspFrozenItemSites.cpp \
           displays/dspGLSeries.cpp \
           displays/dspGLTransactions.cpp \
           displays/dspIncidentsByCRMAccount.cpp \
           displays/dspIndentedBOM.cpp \
           displays/dspIndentedWhereUsed.cpp \
           displays/dspInvalidBillsOfMaterials.cpp \
           displays/dspInventoryAvailabilityByCustomerType.cpp \
           displays/dspInventoryAvailabilityByItem.cpp \
           displays/dspInventoryAvailabilityByParameterList.cpp \
           displays/dspInventoryAvailabilityBySalesOrder.cpp \
           displays/dspInventoryAvailabilityBySourceVendor.cpp \
           displays/dspInventoryAvailabilityByWorkOrder.cpp \
           displays/dspInventoryHistoryBase.cpp \
           displays/dspInventoryHistoryByItem.cpp \
           displays/dspInventoryHistoryByOrderNumber.cpp \
           displays/dspInventoryHistoryByParameterList.cpp \
           displays/dspInventoryLocator.cpp \
           displays/dspInvoiceRegister.cpp \
           displays/dspItemCostDetail.cpp \
           displays/dspItemCostHistory.cpp \
           displays/dspItemCostSummary.cpp \
           displays/dspItemCostsByClassCode.cpp \
           displays/dspItemsByCharacteristic.cpp \
           displays/dspItemsByClassCode.cpp \
           displays/dspItemsByParameter.cpp \
           displays/dspItemsByProductCategory.cpp \
           displays/dspItemSitesByItem.cpp \
           displays/dspItemSitesByParameterList.cpp \
           displays/dspItemSourcesByItem.cpp \
           displays/dspItemSourcesByVendor.cpp \
           displays/dspItemsWithoutItemSources.cpp \
           displays/dspJobCosting.cpp \
           displays/dspJournals.cpp \
           displays/dspMaterialUsageVarianceByBOMItem.cpp \
           displays/dspMaterialUsageVarianceByComponentItem.cpp \
           displays/dspMaterialUsageVarianceByItem.cpp \
           displays/dspMaterialUsageVarianceByWarehouse.cpp \
           displays/dspMaterialUsageVarianceByWorkOrder.cpp \
           displays/dspOrderActivityByProject.cpp \
           displays/dspOrders.cpp \
           displays/dspPartiallyShippedOrders.cpp \
           displays/dspPendingAvailability.cpp \
           displays/dspPendingBOMChanges.cpp \
           displays/dspPlannedOrdersByItem.cpp \
           displays/dspPlannedOrdersByPlannerCode.cpp \
           displays/dspPoDeliveryDateVariancesByItem.cpp \
           displays/dspPoDeliveryDateVariancesByVendor.cpp \
           displays/dspPoHistory.cpp \
           displays/dspPoItemReceivingsByDate.cpp \
           displays/dspPoItemReceivingsByItem.cpp \
           displays/dspPoItemReceivingsByVendor.cpp \
           displays/dspPoItemsByDate.cpp \
           displays/dspPoItemsByItem.cpp \
           displays/dspPoItemsByVendor.cpp \
           displays/dspPoPriceVariancesByItem.cpp \
           displays/dspPoPriceVariancesByVendor.cpp \
           displays/dspPoReturnsByVendor.cpp \
           displays/dspPOsByDate.cpp \
           displays/dspPOsByVendor.cpp \
           displays/dspPricesByCustomer.cpp \
           displays/dspPricesByCustomerType.cpp \
           displays/dspPricesByItem.cpp \
           displays/dspPurchaseReqsByItem.cpp \
           displays/dspPurchaseReqsByPlannerCode.cpp \
           displays/dspQOHByItem.cpp \
           displays/dspQOHByLocation.cpp \
           displays/dspQOHByParameterList.cpp \
           displays/dspQuotesByCustomer.cpp \
           displays/dspQuotesByItem.cpp \
           displays/dspReorderExceptionsByPlannerCode.cpp \
           displays/dspReservations.cpp \
           displays/dspRunningAvailability.cpp \
           displays/dspSalesHistoryByBilltoName.cpp \
           displays/dspSalesHistoryByCustomer.cpp \
           displays/dspSalesHistoryByItem.cpp \
           displays/dspSalesHistoryByParameterList.cpp \
           displays/dspSalesHistoryBySalesrep.cpp \
           displays/dspSalesHistoryByShipTo.cpp \
           displays/dspSalesOrdersByCustomer.cpp \
           displays/dspSalesOrdersByCustomerPO.cpp \
           displays/dspSalesOrdersByItem.cpp \
           displays/dspSalesOrdersByParameterList.cpp \
           displays/dspSalesOrderStatus.cpp \
           displays/dspShipmentsBase.cpp \
           displays/dspShipmentsByDate.cpp \
           displays/dspShipmentsBySalesOrder.cpp \
           displays/dspShipmentsByShipment.cpp \
           displays/dspSingleLevelBOM.cpp \
           displays/dspSingleLevelWhereUsed.cpp \
           displays/dspSlowMovingInventoryByClassCode.cpp \
           displays/dspStandardJournalHistory.cpp \
           displays/dspSubstituteAvailabilityByItem.cpp \
           displays/dspSummarizedBacklogByWarehouse.cpp \
           displays/dspSummarizedBankrecHistory.cpp \
           displays/dspSummarizedBOM.cpp \
           displays/dspSummarizedGLTransactions.cpp \
           displays/dspSummarizedSalesByCustomer.cpp \
           displays/dspSummarizedSalesByCustomerByItem.cpp \
           displays/dspSummarizedSalesByCustomerType.cpp \
           displays/dspSummarizedSalesByCustomerTypeByItem.cpp \
           displays/dspSummarizedSalesByItem.cpp \
           displays/dspSummarizedSalesBySalesRep.cpp \
           displays/dspSummarizedSalesHistoryByShippingZone.cpp \
           displays/dspTimePhasedAvailability.cpp \
           displays/dspTimePhasedBookingsByCustomer.cpp \
           displays/dspTimePhasedBookingsByItem.cpp \
           displays/dspTimePhasedBookingsByProductCategory.cpp \
           displays/dspTimePhasedSalesByCustomer.cpp \
           displays/dspTimePhasedSalesByCustomerByItem.cpp \
           displays/dspTimePhasedSalesByCustomerGroup.cpp \
           displays/dspTimePhasedSalesByItem.cpp \
           displays/dspTimePhasedSalesByProductCategory.cpp \
           displays/dspTimePhasedUsageStatisticsByItem.cpp \
           displays/dspTodoByUserAndIncident.cpp \
           displays/dspTrialBalances.cpp \
           displays/dspUnbalancedQOHByClassCode.cpp \
           displays/dspUndefinedManufacturedItems.cpp \
           displays/dspUninvoicedReceivings.cpp \
           displays/dspUnusedPurchasedItems.cpp \
           displays/dspUsageStatisticsBase.cpp \
           displays/dspUsageStatisticsByClassCode.cpp \
           displays/dspUsageStatisticsByItem.cpp \
           displays/dspUsageStatisticsByItemGroup.cpp \
           displays/dspUsageStatisticsByWarehouse.cpp \
           displays/dspValidLocationsByItem.cpp \
           displays/dspVendorAPHistory.cpp \
           displays/dspVoucherRegister.cpp \
           displays/dspWoHistoryByClassCode.cpp \
           displays/dspWoHistoryByItem.cpp \
           displays/dspWoHistoryByNumber.cpp \
           displays/dspWoMaterialsByItem.cpp \
           displays/dspWoMaterialsByWorkOrder.cpp \
           displays/dspWoScheduleByItem.cpp \
           displays/dspWoScheduleByParameterList.cpp \
           displays/dspWoScheduleByWorkOrder.cpp \
           displays/dspWoSoStatus.cpp \
           displays/dspWoSoStatusMismatch.cpp

